### Initializing Different Types of arrays

In [1]:
import numpy as np

In [2]:
#All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [3]:
# all 1s matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
#any other no.
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [5]:
a = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(a)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [6]:
#any other no. (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [7]:
# random decimal no.
np.random.rand(4,2)

array([[0.39507716, 0.73616279],
       [0.68970919, 0.28305555],
       [0.77496385, 0.96512027],
       [0.27951234, 0.77062158]])

In [8]:
#random integer values
np.random.randint(4,size=(3,3))


array([[3, 3, 1],
       [2, 1, 1],
       [0, 3, 3]])

In [9]:
#indentity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
#repeat the no. of array
arr = np.array([1,3,4])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 3 3 3 4 4 4]


In [11]:
#repeat in 2d array
arr = np.array([[1,3,4]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 3 4]
 [1 3 4]
 [1 3 4]]


In [12]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1]= 9
output[1:4,1:4]= z
print(z)
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be carefull when copying!!!

In [13]:
a = np.array([1,2,3])
# b= a
#b output = [1,2,3]
b = a.copy()
b[0]= 100
print(b)
print(a)
#output = [100,2,3] so thats why we use copy function

[100   2   3]
[1 2 3]


### Mathematics

In [14]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
a +=2
a

array([3, 4, 5, 6])

In [16]:
a-2


array([1, 2, 3, 4])

In [17]:
a*2

array([ 6,  8, 10, 12])

In [18]:
a / 2

array([1.5, 2. , 2.5, 3. ])

In [19]:
a**2

array([ 9, 16, 25, 36])

In [20]:
a//2

array([1, 2, 2, 3], dtype=int32)

In [21]:
b = np.array([1,2,3,4])
a+b

array([ 4,  6,  8, 10])

In [22]:
#take sin of this value
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

### Linear algebra

In [23]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [24]:
#find the determenent
c = np.identity(3)
np.linalg.det(c)

1.0

#### statistics

In [25]:
stats = np.array([[1,2,3],[4,5,6]])
stats 

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.min(stats)

1

In [27]:
np.max(stats)

6

### Reorganizing arrays 

In [28]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [29]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Miscellaneous

#### Load data from file'


In [41]:
filedata=np.genfromtxt('D:\Mine\\name.txt', delimiter=',')
filedata

array([nan,  4.,  5., nan])

#### Boolean Masking and Advance indexing

In [42]:
filedata>50


array([False, False, False, False])