In [1]:
import numpy as np


In [2]:
a = np.array([1,2,4])
print(a)

[1 2 4]


In [3]:
b = np.array([[3,45,67,7,8,8],[4,56,6,7,8,7]])
print(b)

[[ 3 45 67  7  8  8]
 [ 4 56  6  7  8  7]]


In [4]:
# get dimention
a.ndim

1

In [5]:
#get shape
b.shape

(2, 6)

In [6]:
#get type
a.dtype

dtype('int32')

In [7]:
#get size
a.itemsize


4

In [8]:
#get total size
a.size


3

# accessing/changing specific rows columns,etc

In [9]:
c = np.array([[1,3,4,5],[5,6,7,7]])
print(c)

[[1 3 4 5]
 [5 6 7 7]]


In [12]:
# get a specific element[r,c]
c[1, 3]


7

In [13]:
# get a specific row
c[0, :]

array([1, 3, 4, 5])

In [14]:
# get a specific column
c[: ,2]

array([4, 7])

In [15]:
#getting a little more fancy[startindex:endindex:stepsize]
c[0,1:3:2]

array([3])

#### 3d Examples


In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
#get specific element
b[0,1,1]

4

In [19]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [20]:
# replace
b[:,1,:] = [[9,9],[8,8]]

In [21]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])